
	 vim:linebreak:nowrap:nospell:cul tw=78 fo=tqlnr foldcolumn=3 
--- 
title: Template for .Rmd 
date: "`r paste('last updated', 
    format(lubridate::now(), '%H:%M, %d %B %Y'))`"
output: 
  pdf_document: 
    latex_engine: xelatex
toc: TRUE 
toc_depth:  1 
fontsize: 12pt 
geometry: margin=0.5in,top=0.25in 
---

From httr github/demos for google

<!-- 
vim: to format all urls for md
s/https.*/[&]()/g
-->

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = TRUE)
library(jimTools)
library(httr)
```

## Initialization,  need only do once.
## Set up the token, .httr-oauth

### Endpoints
```{r endpoints}

# 1. Find OAuth settings for google:
#    https://developers.google.com/accounts/docs/OAuth2InstalledApp
oauth_endpoints("google")

```
```{r register}

# 2. Register an application at https://cloud.google.com/console#/project
#    Replace key and secret below.
#    NOTE:  google calls this key as "Client ID"
myapp <- oauth_app("google",
key="254738439744-0rl7a94t125fbkam9nlkg63p1sm1ski6.apps.googleusercontent.com",
secret="OjEJig9Mj1QIoo4K07tkp7_B"
)
myapp
```
```{r .httr-oauth}

# This creates .httr-oauth (binary) in project root  (IF it does not yet
exist)
# BEST:   run this in st (X11) b/c need to approve 
# 3. Get OAuth credentials
google_token <- oauth2.0_token(
                  oauth_endpoints("google"), 
                  myapp,
                  scope = "https://www.googleapis.com/auth/userinfo.profile"
)

```
```{r use_api}

# 4. Use API (auto-refreshs a stale OAuth token)
req <- GET(
  "https://www.googleapis.com/oauth2/v1/userinfo",
  config(token = google_token)
)
stop_for_status(req)
content(req)
```

```{r one_video}

if (!exists("api")) api <- get_api_codes()

# initial global values | set .httr_oauth


l <- get_typical_yt()
maxResults  <- l$maxResults
playlistId  <- l$playlistId
video_id = l$videoId
base_url <- "https://www.googleapis.com/youtube/v3/videos"


api_opts <- list(part = "snippet",
                 id = video_id,
                 maxResults = maxResults,
                 fields="items(snippet(title))",
                 key = api$api_key)

r <- httr::GET(base_url, query = api_opts) 
httr::content(r)

```


***

```{r knit_exit()} 
knitr::knit_exit()
```

/newpage

```{r render, eval=FALSE	} 
file <- ""
file  <- basename(file)
dir <- "rmd"

jimTools::ren_pdf(file,dir)
jimTools::ren_github(file, dir)
```
