---
title: Template for .Rmd
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

## ======================================
#### 001_get_comments, for GIVEN video
## ======================================

```{r setup, include=FALSE		}
knitr::opts_chunk$set(
    echo = TRUE,
    comment = "      ##",
    error = TRUE, 
    collapse = TRUE)
load_all()
```

```{r api_key}
if (!exists("api")) api <- get_api_codes()
api
```

```{r initialize}
base_url <- "https://www.googleapis.com/youtube/v3/commentThreads"
if (!exists("l")) l  <- get_typical_values()

# spare:
#playlistId  <- "PLbcglKxZP5PMZ7afIT7E2o9NwQIzqTI5l"

```

```{r query}
# fields , careful if split on mutliple lines, use paste
query  <- list(
  part = "snippet,replies",
  maxResults = l$maxResults,
  fields = paste(sep = ", ", "nextPageToken",
  "items(snippet(topLevelComment(snippet(videoId,textDisplay))))"
   ),
  key = api$api_key,
  pageToken = NULL,
  videoId = l$videoId)

```

Auth_code
```{r get_auth_code}
auth.code  <- getOption("auth.code")
auth.code
```

## HELPER:

More batches?
*  Helper function: 
*  Get next page token
*  Run GET again,  return next r

```{r get_batch}
get_batch  <- function() {
  r <- httr::GET(base_url, 
  query = query,
  config = httr::config(token = auth.code))  %>% 
  httr::stop_for_status()
}
```
From r, process comments
*  Helper function
*  Process comments into tibblel
*  Rbind with prior batches, return 

```{r process_comments}
process_comments  <- function(r, comments = tibble::tibble()) {
  json_content <- get_json(r)
  next_comments <- json_content$items$snippet$topLevelComment$snippet
  #browser()
  next_comments  <- tibble::as_tibble(next_comments)
  comments <- rbind(comments, next_comments)
}
```
***


## 1st batch
```{r get}
comments  <- NULL
r  <- get_batch()

r

comments  <- process_comments(r)
```

Main loop:   remaining batches
```{r main_loop}

while ( !is.null(httr::content(r)$nextPageToken )) {
  query$pageToken  <- httr::content(r)$nextPageToken
	r  <- get_batch()
	comments  <- process_comments(r, comments)

} # end loop
```
```{r examine_comments}

comments
head(comments)
saveRDS(comments, file=here("data","comments.RDS"))
```





```{r trick_tibble, eval=FALSE  , include=FALSE }

# Observe,  rind (A, B)
# A is empty tibble,
# B is tibble
# Then rbind success and returns combined

comments  <- tibble::tibble()
comments
new_comments  <- tibble::tribble(
                         ~x, ~y,
                         1, 0,
                         0, 1)

z   <- rbind(comments, new_comments)
z
x
```


```{r render, eval=FALSE, include=FALSE 	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root

file  <- here("", "")
file  <- "rmd/009_comments.Rmd"

# in general, pdf will look nicer
rmarkdown::render(file,
                  #output_format = "pdf_document",
                  output_format = "html_document",
                  output_file = "~/Downloads/print_and_delete/out")
```
