---
title: Template for .Rmd
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

/home/jim/code/pkg_yt_api/exclude/011_playlists.Rmd

---- PURPOSE ----
given a channel_id , return list of all playlists
----------------
```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE)
```

```{r library, include=FALSE		}
load_all()
```
```{r render, eval=FALSE	}
here()
file <- "011_playlists.Rmd"
file  <- basename(file)
dir="rmd"

```
```{r initialize}
if (!exists("api")) api  <- get_api_codes()
if (!exists("l"))   l    <- get_typical_values()
base_url <- "https://www.googleapis.com/youtube/v3/playlists"
```

Auth_code
```{r get_auth_code}
auth.code  <- getOption("auth.code")
auth.code
```

```{r get_count_playlists}

```


TODO - not returning nextPageToken (actually, it is, just toofwe playlists!)
```{r query}
query  <- list( 
			part="snippet",
			channelId = l$channelId,
			maxResults = l$maxResults,
      fields=paste(sep=",", 
                   "nextPageToken",
                  "items(id,snippet(title,description,channelId,publishedAt))"
                  ),
			key = api$api_key,
			pageToken = NULL)

```
```{r HEAD}

r <- httr::HEAD(base_url, 
           query = query,
					 config = httr::config( token = auth.code))
r

```

```{r call }
r <- httr::GET(base_url, 
           query = query,
					 config = httr::config( token = auth.code)) %>% 
						 httr::stop_for_status()

           r
json_content <- get_json(r)

# playlists is data.frame, 50 x 4
playlists <- json_content$items$snippet
t   <- tibble::as_tibble(playlists)
t

```
```{r next}

```



```{r repeat}
while ( !is.null(get_nextPageToken(r)) ) {
		# only 1 change
		query$pageToken <- get_nextPageToken(r)

		r <- httr::GET(base_url, 
									query = query,
									config = config 
									)

		json_content <- get_json(r)
		next_playlists <- json_content$items$snippet

		playlists <- rbind(playlists, next_playlists)
}
```
```{r}
saveRDS(playlists, file=here("data", "playlists.RDS"))
```

post-processing
```{r}
# google stores dates as ISO 8601, as string
# why need TWO lubridate commands to retrieve simple date?
playlists <- playlists %>% 
	dplyr::mutate(date= lubridate::as_date(
									lubridate::as_datetime(publishedAt))) %>% 
	dplyr::select(-c(channelId,publishedAt))

playlists


```
