---
title: Template for .Rmd
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

pkg_yt_api/exclude/012_playlistitems.Rmd

---- PURPOSE ----
given a playlist, return list of videos
----------------

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  comment="      ##",  error=TRUE, collapse=TRUE)
```

```{r library, include=FALSE		}
library(jimTools)
library(here)
library(dplyr)
library(magrittr)
load_all()
```

```{r render, eval=FALSE	}
here()
file <- "/home/jim/code/r_rafael/rmd/005_linear_algebra_examples.Rmd"
file  <- basename(file)
dir="rmd"

jimTools::ren_pdf(file,dir)
jimTools::ren_github(file, dir)
```

```{r token}
api  <- get_api_codes()
# set .httr_oauth  and token
# default uses scope="ssl
myapp  <- tuber::yt_oauth(app_id = api$oauth2_id,
													app_secret = api$oauth2_secret)
```
```{r initialize}

base_url <- "https://www.googleapis.com/youtube/v3/playlistItems"
l <- get_typical_yt()
maxResults  <- l$maxResults
playlistId  <- l$playlistId
google_token = base::getOption("google_token") 
config  <- set_config(google_token)

# https://www.youtube.com/playlist?list=PLbcglKxZP5PMZ7afIT7E2o9NwQIzqTI5l
playlistId  <- "PLbcglKxZP5PMZ7afIT7E2o9NwQIzqTI5l"

```

```{r query}
# =================
# 002_setup call
# ================
query  <- set_query(part="snippet",
                maxResults=maxResults,
                playlistId=playlistId,
                pageToken="",
								mine=FALSE,
                fields=
"nextPageToken, items(snippet(title, description, position))",
                key=api$api_key)

# what si this?
config  <- set_config(google_token)
config  <- set_config(myapp)

get_all_videos  <- function(url,query,config){

	r  <- get_batch_videos(base_url, query, config)
	json_content <- get_json(r)
	videos <- json_content$items$snippet

		# if multiple blocks, loop
		while ( !is.null(get_nextPageToken(r)) ) {
				query$pageToken  <- get_nextPageToken(r)
				r<- get_batch_videos(url = base_url, query,config)

				# process
				json_content <- get_json(r)
				next_videos <- json_content$items$snippet
				videos <- rbind(videos, next_videos)
		}	# end loop
	return (videos)
}

# 957 x 3 
videos <- get_all_videos(base_url,query,config)

str(videos)
head(videos)
## jump to bottom

query$playlistId <- "PLbcglKxZP5PMU2rNPBpYIzLTgzd5aOHw2"  # 60s, 133
next_videos  <- get_all_videos(url,query,config)

videos <- rbind(videos, next_videos)


## have videos
## SAVE
here::here()
saveRDS(videos, file=here::here("data/videos.RDS"))



t  <- videos %>% select(title, position)
str(t)
head(t)
str(t)
t  <- t %>% dplyr::arrange(title)
head(t$title)

```



```{r knit_exit()}
knitr::knit_exit()
```

***






