---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
    fontsize: 11pt   
    geometry: margin=0.5in,top=0.25in   
---

---- PURPOSE ----
given ONE playlist, return list of videos
----------------

### SEE 013_get_all_videos.Rmd
*   retrieve ALL videos for ALL playlists

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment="      ##",  
                      error=TRUE, 
                      collapse=TRUE)
load_all()
```

```{r initialize}
initialize <- function() {

  auth.code  <- readRDS(here("saved_auth_code"))

  # prep for GET
  if (!exists("api")) api <- get_api_codes()

  if (!exists("l")) l <- get_typical_values()

  base_url <- "https://www.googleapis.com/youtube/v3/playlistItems"

  r  <- structure(list(auth.code = auth.code,
                       base_url = base_url,
                       api = api,
                       l = l)

  )
  
}
```

### get_query()
```{r query}
# return query, run only once
get_query  <- function(playlistId, api, l) {
    query  <- list(
                    part="snippet",  
                    maxResults=l$maxResults,  
                    playlistId= l$playlistId,	
                    fields=paste(
                            sep=", ",   
                           "nextPageToken",   
                           "items(snippet(title, description, position ))"  
                        ),  
                    key=api$api_key
    )  
}



```

### check against HEAD
```{r}
# TODO  - how to check?
r  <- httr::HEAD(url =  base_url,
                query = query,
                config = config 
                )

r
```

### process_batch()
```{r process}
# Given an r, extract the videos and nextPageToken (as list) 
process_batch <- function(r) {
  json_content <- get_json(r)
  videos <- json_content$items$snippet
  nextPageToken <- json_content$nextPageToken
  list(
    nextPageToken = nextPageToken,
    videos = videos
  )
}

```

### get_next_batch_videos
```{r next_batch}

get_next_batch_videos   <- function(base_url, query, config) {
      r  <- httr::GET(url =  base_url, 
                      query = query, 
                      config = config)

			# process
      l <- process_batch(r)
}

```

combine 1st batch + additional (if any)
```{r all_videos_ONE_playlist}
get_playlist_videos <- function(playlistId) {
  r  <- initialize()
  api = r$api
  l  <- r$l
  auth.code  <- r$auth.code
  base_url  <- r$base_url

  query  <- get_query(playlistId, api, l)
  config  <- config  <-  httr::config(token = auth.code)

  # run 1st time (may refresh stale token)
  l <- get_next_batch_videos(base_url, query, config)
  videos <- l$videos
  nextPageToken <- l$nextPageToken

  while (!is.null(nextPageToken)) {
    query$pageToken <- nextPageToken
    l <- get_next_batch_videos(base_url, query, config)
    videos <- rbind(videos, l$videos)
    nextPageToken <- l$nextPageToken
  }
  videos
}
playlistId  <- "PLbcglKxZP5PMU2rNPBpYIzLTgzd5aOHw2"
videos  <- get_playlist_videos(playlistId)
head(videos, 2)

```


```{r}
saveRDS(videos, file=here::here("data/videos.RDS"))
```

```{r}

```
cleanup videos
```{r cleanup}
t  <- videos %>% dplyr::select(title, position) %>% 
	dplyr::arrange(title)
t
str(t)
```

```{r render, eval=FALSE	}
here()
file <- "rmd/012_get_videos.Rmd"
file  <- basename(file)
dir="rmd"

jimTools::ren_pdf(file,dir)
jimTools::ren_github(file, dir)
```
